### ISSUE TITLE
Maintain key and total on resetKey vs deleting

### ISSUE THREAD

**Issue by angelo0000** [2do2go/rate-limit-mongo#26]
Is there a configuration that allows to set the counter to 0 vs it deleting the record?   It would be a great addition to have an additional field for total and when the resetKey is called it resets the counter to 0 and increments the total.  This could allow for easily being able to see who has been hitting your server.  Currently you could have someone hitting your sever but you not know it b/c the key is deleted after the expiration.  I get why the in memory store or redis store wouldn't want this but for a persistent store like mongo it would be a big bonus imo.

**Comment by okv** [comment]
Hi, there.
I got your point and I agree that it might be useful in some situations to have an ability to know actual ips.
But unfortunately, it's really hard to implement, because current store implementation relies on mongodb ttl indexes. So normally mongodb removes expired keys (without using `resetKey` method). Looks like there is no way to do it without cleaning up the collection manually which is highly not desired because of the increasing complexity of the store implementation.

**Comment by okv** [comment]
I'm closing it...

**Comment by angelo0000** [comment]
Got it.. no worries.. thanks for the response.  I guess at the end of they day we can easily implement our own collection counter for a route such as /api as middleware to increment a counter for an IP.

**Comment by okv** [comment]
You're welcome. Yes, there is always a place for custom implementation :)
